---
baseURL: https://npanic.br0.space/
languageCode: en-us
title: Martin Friedrich
theme: toha
googleAnalytics: UA-105747174-1

languages:
  en:
    languageName: English
    weight: 1

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  highlight:
    guessSyntax: true

enableEmoji: true
enableGitInfo: true

params:
  background: /images/site/the_eye.png
  logo:
    main: /images/terminal.svg
    inverted: /images/terminal_inverted.svg
    favicon: /images/site/favicon.png

  gitRepo: https://github.com/networkpanic/npanic.br0.space
  gitBranch: main

  enableBlogPost: false
  enableTOC: true
  # Show tags under the post title
  enableTags: true
  newsletter:
    enable: false
  darkMode:
    enable: true
    provider: darkreader
    default: system
  showFlags: false
  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: false
    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: false
